# Generated by Django 4.0.1 on 2022-01-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_produkt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produkt',
            new_name='Product',
        ),
    ]
