# Generated by Django 3.1.8 on 2022-02-10 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 19, 51, 8, 726532, tzinfo=utc)),
        ),
    ]
