# Generated by Django 4.0.1 on 2022-01-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_produkt_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
    ]
