# Generated by Django 3.1.8 on 2022-02-10 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220210_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 19, 53, 19, 335909, tzinfo=utc)),
        ),
    ]
