# Generated by Django 3.1.8 on 2022-02-10 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220210_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 20, 46, 15, 190432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product'),
        ),
    ]
