# Generated by Django 3.1.8 on 2022-02-11 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220210_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 21, 46, 32, 510770, tzinfo=utc)),
        ),
    ]
